### PR TITLE
Feature: Listing Comments (Q&A on Products)

### PR DESCRIPTION
**Pull request by AllienWorks**
listing-comments

- see [PD-490](https://particl.atlassian.net/browse/PD-490)
- updated new Listing detail layout for Comments
- Commenting layout (Add new, comment list, answers etc.)

All TODOs documented in code (`FIXMEs` & `TODOs`).

### CODE REVIEW

**Comment by zaSmilingIdiot** [comment]
Implementation details still to be added

**Comment by AllienWorks** [comment]
Just a friendly reminder that the longer we'll wait with implementing this, the bigger merging hell it will be in the future :)

**Comment by zaSmilingIdiot** [comment]
Might be helpful to incorporate the changes in https://github.com/particl/particl-desktop/pull/1335 (updated dependencies)

**Comment by HenkSwardt** [comment]
Implementation of these designs will happen on the following two task:

https://particl.atlassian.net/browse/PBD-206 - MP - Implement Public Comments
https://particl.atlassian.net/browse/PBD-207 - GUI - Implement Public Comments

**Comment by zaSmilingIdiot** [comment]
Closing this due to re-organization of this repo. Pull request owner is aware of the update, and will be able to re-submit this PR when/where applicable.

Note: has already been migrated

**Pull request closed without merging**
