### PR TITLE
Release/1.1.0

### PR DESCRIPTION
**Pull request by kewde**

### CODE REVIEW

**Comment by vikas-cis** [comment]
I can't see close button over the sync modal Is that removed for some reason ?
screen shot 2018-01-25 at 2 39 30 pm

**Comment by vikas-cis** [comment]
@pciavald Can't able to disable colstaking, Popup stills shows button disable 

screen shot 2018-01-25 at 3 46 49 pm

**Comment by vikas-cis** [comment]
@pciavald Seems zap progress doesn't update when you do zapping. It only  works when restart the app again.

screen shot 2018-01-25 at 3 57 23 pm

**Comment by pciavald** [comment]
peek 2018-01-27 13-34

**Comment by pciavald** [comment]
Looks like a floating point problem

screenshot_20180127_133524

**Comment by pciavald** [comment]
cold staking status is not updated even after confirmation and reloading the overview page
screenshot_20180127_133729

**Comment by pciavald** [comment]
@anandsinghparihar @vikas-cis can you please look into this

**Comment by HenkSwardt** [comment]
Hi @pciavald 

Just to prevent confusion, @kewde was saying that he was looking into this task. 

Can we please confirm?

Thanks

**Comment by pciavald** [comment]
thanks @kewde I will review that today

**Comment by vikas-cis** [comment]
@kewde looks fine to me 👍

**Pull request merged**
