### PR TITLE
ctrl+v issue fix for OSX

### PR DESCRIPTION
**Pull request by vikas-cis**
#710

### CODE REVIEW

**Comment by pciavald** [comment]
@vikas-cis does this work for command+V ? ctrl+V is not standard at all on OSX.

**Comment by vikas-cis** [comment]
@pciavald it will work for both 

thanks

**Comment by pciavald** [comment]
that pastes twice on linux

**Comment by vikas-cis** [comment]
thanks @anandsinghparihar  I just want multiple people can test on different machine so we have clear look of the functionality that implemented works on different machine  👍

**Comment by pciavald** [comment]
@vikas-cis can you try to make @coveralls happy ? I'll test again

**Comment by pciavald** [comment]
works on linux and windows. Also works on Mac with both cmd+V and ctrl+V, which i think we do not want. Ctrl+V is not a way to paste on mac, only cmd+V should work.

**Comment by vikas-cis** [comment]
@pciavald I was just wondering if user change the setting from preference ?

Thanks

**Comment by pciavald** [comment]
@vikas-cis on mac you can change the order of keys (command, ctrl, alt) so that command is triggered when you push the ctrl key, but the actual paste at the OS level is with command+V even though you can configure to press ctrl, afaik.

**Comment by kewde** [comment]
To be honest, I don't think we should allow CTRL + V on _one_ component and not on the others.
Either we do this for the whole application, or not at all.

**Comment by pciavald** [comment]
@kewde before merging we should test it on win, mac & linux

**Pull request merged**
