### PR TITLE
Market

### PR DESCRIPTION
**Pull request by AllienWorks**
> **Work in progress, don't merge**

### CODE REVIEW

**Comment by pciavald** [comment]
@HenkSwardt let's discuss the milestone of this in scrum

**Comment by vikas-cis** [comment]
`webpack: Compiled with warnings.
ERROR in src/app/wallet/overview/overview.component.ts(15,3): error TS2392: Multiple constructor implementations are not allowed.
src/app/wallet/overview/overview.component.ts(17,3): error TS2392: Multiple constructor implementations are not allowed.`

I have taken latest pull and got this :P

**Comment by vikas-cis** [comment]
I have fixed that and pushed the commit 

Thanks

**Comment by zaSmilingIdiot** [comment]
No longer necessary for this pull request

**Pull request closed without merging**
