### PR TITLE
Updates dependencies (develop branch)

### PR DESCRIPTION
**Pull request by zaSmilingIdiot**
Updates dependencies on the develop branch for the mainnet desktop wallet.

This change updates the application to make use of Angular 7.2

### CODE REVIEW

**Comment by zaSmilingIdiot** [comment]
@AllienWorks Would you mind having a look over the changes made in this branch (for the current mainnet wallet)? The angular/material dependenices have been updated, so I just want confirmation that everything still looks visually correct.

**Review by AllienWorks — CHANGES_REQUESTED** [review]
- [x] Overview, History: TX table spans wider than it should
- [x] Address Book: address details modal is weird, with duplicated QR codes
- [x] Receive > Private address: addy string not wrapped/formatted properly

### TODO

- [ ] wallet stucks when encrypting (at daemon restart)
- [ ] Address Book: filtering by type broken
- [ ] pagination seems to be broken (changing rows per page)

**Comment by AllienWorks** [comment]
Note to self:
- comment-out `index.html:5` (meta Content-Security-Policy)
- run with `ng serve` and `yarn start:electron:dev -- -testnet -rpcport=51935`

**Comment by AllienWorks** [comment]
My sync was stuck, so I reindexed, but then I got this one:
```
2019-04-09T10:38:31Z UpdateTip: new best=dc5e8f7c96bb15e82f12abeb61ca35e36a1c2b675d0e5cccb7b08bcdae807a24 height=343944 version=0x000000a0 log2_work=66.012252 tx=370869 date='2019-02-18T13:54:24Z' progress=0.934842 cache=61.6MiB(379923txo)
2019-04-09T10:38:31Z Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there
2019-04-09T10:38:36Z InvalidChainFound: invalid block=fc035a5c183994f81e8e62d29f81c1387b8e9ca131d3b905d930e9dbd579d796  height=343945  log2_work=66.012255  date=2019-02-18T13:57:52Z
2019-04-09T10:38:36Z InvalidChainFound:  current best=dc5e8f7c96bb15e82f12abeb61ca35e36a1c2b675d0e5cccb7b08bcdae807a24  height=343944  log2_work=66.012252  date=2019-02-18T13:54:24Z
2019-04-09T10:38:36Z ERROR: ProcessNewBlock: AcceptBlock FAILED (bad-ctout-rangeproof-verify, Transaction check failed (tx hash b0d3330cd28e2d6a24036a530bb1ae492f4a7d2f245c83d64b0d7fdc5c200c8d)  (code 16))
```

**Comment by zaSmilingIdiot** [comment]
Attempting this build again, now with an edited github_token so that at least the github posting works.

**Comment by zaSmilingIdiot** [comment]
As the build credentials seem to have an invalid github token, I'll post next the build message generated by the last commit

**Comment by zaSmilingIdiot** [comment]
3d023be +build +request This is a community test build and feedback is always welcome. Please log any issues found on https://github.com/particl/particl-desktop/issues or for assistance stop by one of the particl official communication platform testing channels/rooms. PLEASE NOTE: this is an update to the current mainnet wallet, which is currently version v1. This build will be a required update for the version 1 releases in order to continue using the application after the 2019-07-16 hardfork. Your assistance in testing it is very much appreciated.
Note: the download links expire after 10 days.
 ```
 de70b2b1b90a27f59cef8e3c6d217c1a866cc95cbc7283f85b8c07d74c3908e6 particl-desktop-linux-amd64-PR1519-3d023be.deb
 https://transfer.sh/2UIHM/particl-desktop-linux-amd64-PR1519-3d023be.deb
 http://jxm5d6emw5rknovg.onion/2UIHM/particl-desktop-linux-amd64-PR1519-3d023be.deb
 ```
 ```
 df873d4993dfa105c69eabbf120511310f5d145a48a632c6c0a98b326eaf76ff particl-desktop-linux-x64-PR1519-3d023be.zip
 https://transfer.sh/IdZaV/particl-desktop-linux-x64-PR1519-3d023be.zip
 http://jxm5d6emw5rknovg.onion/IdZaV/particl-desktop-linux-x64-PR1519-3d023be.zip
 ```
 ```
 9e7df7f419433fed3667cb75a265c9b32df42eb7441d480fb2fa1c412c9381ad particl-desktop-mac-PR1519-3d023be.zip
 https://transfer.sh/8DgqD/particl-desktop-mac-PR1519-3d023be.zip
 http://jxm5d6emw5rknovg.onion/8DgqD/particl-desktop-mac-PR1519-3d023be.zip
 ```
 ```
 8d272a79dc6e9af3220dbffd797ac607cec08451b44c312c2ac5a85752bef970 particl-desktop-win-ia32-PR1519-3d023be.zip
 https://transfer.sh/gyX8L/particl-desktop-win-ia32-PR1519-3d023be.zip
 http://jxm5d6emw5rknovg.onion/gyX8L/particl-desktop-win-ia32-PR1519-3d023be.zip
 ```
 ```
 54e724d6694dc41d0866b5cc34931232ea39fd02bf60c5b49e2308410d8cd776 particl-desktop-win-x64-PR1519-3d023be.zip
 https://transfer.sh/vr3sq/particl-desktop-win-x64-PR1519-3d023be.zip
 http://jxm5d6emw5rknovg.onion/vr3sq/particl-desktop-win-x64-PR1519-3d023be.zip
 ```

**Comment by zaSmilingIdiot** [comment]
Just need someone to approve this so we can bring the changes into the develop branch. They are already on the 1.4.0 branch, from which the release has been generated. I'm not able to submit the PR and approve it, for the develop branch.

**Review by AllienWorks — APPROVED** [review]

**Comment by zaSmilingIdiot** [comment]
Changes included here are available in the `1.4.0` branch which has been used to release the v1.4 releases. This PR is no longer necessary: the existing changes can be merged in from the `1.4.0` branch.

**Pull request closed without merging**
