### PR TITLE
Fix/debug console history

### PR DESCRIPTION
**Pull request by claudiocabral**
@pciavald This PR solves #814  by not disabling the input form and disabling preventing default event actions when arrow up, down and enter keys are pressed.

### CODE REVIEW

**Comment by claudiocabral** [comment]
Travis build 3342 seems to have failed to `npm install -g @angular/cli`, @kewde do you think you could trigger a rebuild? Since I didn't touch travis or json files I got a feeling my changes did not cause this.

**Comment by pciavald** [comment]
@claudiocabral i've retriggered it

**Comment by HenkSwardt** [comment]
Please confirm if this can be merged?

Thank you for the input @claudiocabral , really appreciated.

**Comment by kewde** [comment]
There is no debug history in 1.1.0 so we can merge this into develop, with no backport to 1.1.0

**Pull request merged**
