### PR TITLE
Resolve lint & unit test cases

### PR DESCRIPTION
**Pull request by anandsinghparihar**

### CODE REVIEW

**Comment by anandsinghparihar** [comment]
some of the test cases like `Angular Infinite Scroll` component test cases still not resolve

**Comment by rynomster** [comment]
```
ERROR: /home/travis/build/particl/particl-desktop/src/app/market/sell/add-item/add-item.component.ts[107, 19]: expected parameter: 'event' to have a typedef
ERROR: /home/travis/build/particl/particl-desktop/src/app/market/sell/add-item/add-item.component.ts[110, 23]: Shadowed name: 'event'
ERROR: /home/travis/build/particl/particl-desktop/src/app/market/sell/add-item/add-item.component.ts[141, 17]: expected parameter: 'index' to have a typedef
ERROR: /home/travis/build/particl/particl-desktop/src/app/market/sell/add-item/add-item.component.ts[148, 18]: expected parameter: 'index' to have a typedef
Lint errors found in the listed files.
```

**Comment by anandsinghparihar** [comment]
@rynomster my bad, I just check out that conflicted file and forgot to resolve lint issue let me quickly resolve it

**Comment by HenkSwardt** [comment]
fixes https://github.com/particl/particl-desktop/issues/909

**Pull request merged**
