### PR TITLE
Modal fix electron

### PR DESCRIPTION
**Pull request by rynomster**
Looks like its finally working.. css hacks :) The issue seems related to relative positioned elements inside a static positioned element.

### CODE REVIEW

**Comment by vikas-cis** [comment]
@rynomster it works perfect to me on OSX .

Thanks

**Comment by rynomster** [comment]
@allienworks when you get a chance could you have a look for us? :)

**Comment by allienworks** [comment]
@rynomster seems to work fine for me. However I haven't this issue in this wallet/branch (I'm on Linux).

The main problem is, and I've said this so many times, that this is **not only** issue of modals, but everything that's animated. Check `market` branch, go to Buy and click through _Cart > Shipping > Confirm_.

**Comment by rynomster** [comment]
Right now the most pressing issue is releasing the current release. Muon
doesn't work on Linux without a manual work around, and other things crash
on muon, so an electron release to get 1.1.0 out is the most obvious
release.. We can do the same fix for the other stuff, but chances are we
have some time to get it right before the MP release, and electron or Muon
also have some time.

**Comment by allienworks** [comment]
Yeah, I just want us to keep in mind those other issues as well, regarding the future ahead. Agreed that the stepper etc. is not needed in 1.1, so we can definitely go with this fix for now.

**Pull request merged**
