### PR TITLE
initilizing the favorites when there is no favorite available

### PR DESCRIPTION
**Pull request by vikas-cis-zz**
https://particl.atlassian.net/browse/PBD-225

### CODE REVIEW

**Comment by vikas-cis-zz** [comment]
#1437 
Thanks

**Comment by zaSmilingIdiot** [comment]
This doesn't, at this point in time, actually fix the linked issue. I'm assuming that the change included here is a part of the fix, but its not a complete solution for the reported issue.

This change appears to modify the behaviour of the component when the favourite items reach nothing. But the reported issue is that when a favourite item is marked as not being a favourite (the favourite indication is unselected), then the item remain visible in th eFavourites page until the page is refreshed. In other words, the Favourites page is not automatically refreshing when a favourited item is removed.

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot I see may be I didn't read the ticket very well my bad :P :D 

Thanks

**Comment by zaSmilingIdiot** [comment]
Previous commentary from me can be ignored

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
