### PR TITLE
enable/display Anon features

### PR DESCRIPTION
**Pull request by AllienWorks**
Not to be merged into 1.1.0 stable release!

- displayed Anon balance
- enabled Anon in Send/Balance transfer

### TODO

- [x] automatically display Anon only on testnet (balance and radio in Send/Transfer)

### CODE REVIEW

**Comment by vikas-cis** [comment]
@allienworks I am looking in to it

**Comment by kewde** [comment]
```
<<<<<<< enhancement/enable-anon
        <mat-radio-button *ngIf="testnet" class="balance" value="anon_balance" fxFlex>
=======
        <mat-radio-button class="balance" value="anon_balance" fxFlex disabled matTooltip="Not available – Anon transactions are currently being tested by researchers from NJIT">
>>>>>>> develop
```
I've used the enhancement/enable-anon one.

**Comment by vikas-cis** [comment]
@kewde what to do with this branch then should we close it ?

**Comment by allienworks** [comment]
> @kewde I've used the enhancement/enable-anon one.

I think that's OK. Less pain and we won't confuse users with disabled features. LGTM

**Comment by AllienWorks** [comment]
@kewde @pciavald isn't this free to merge already?

**Comment by kewde** [comment]
@AllienWorks going to merge today

**Comment by kewde** [comment]
Fixed test, should be good to merge

**Comment by kewde** [comment]
Cleared travis cache, rerunning

**Pull request merged**
