### PR TITLE
[PBD-233] MP/GUI - Multi wallet implementation (Old branch investigation)

### PR DESCRIPTION
**Pull request by spazzymoto**
Merged the old multi wallet branch into the current market branch.

Ensured that market only starts up and shuts down on a certain wallet.

### CODE REVIEW

**Comment by AllienWorks** [comment]
Whoever is responsible for this mess, I want to see them after class! :)

Joking aside, I made some fixes of the layout, but still needs finishing touches.. However cold staking modal (on Overview) is broken:

> ERROR Error: No component factory found for ColdstakeComponent. Did you add it to @NgModule.entryComponents?

It's the only one not working (from what I've tested), so if anybody can look into it.. ;)

**Comment by zaSmilingIdiot** [comment]
Thanks @AllienWorks for the styling updates :smiley: 

I'll take a look into the cold staking component <- thanks for mentioning that.

**Comment by vikas-cis-zz** [comment]
> Whoever is responsible for this mess, I want to see them after class! :)
> 
> Joking aside, I made some fixes of the layout, but still needs finishing touches.. However cold staking modal (on Overview) is broken:
> 
> > ERROR Error: No component factory found for ColdstakeComponent. Did you add it to @NgModule.entryComponents?
> 
> It's the only one not working (from what I've tested), so if anybody can look into it.. ;)

It seems to working fine to me @AllienWorks

**Comment by AllienWorks** [comment]
Also, balances overview in sidebar (under logo) are missing. Maybe an issue of merging / conflicts (in `src/app/core-ui/main/main-view.module.ts`?).

I will still push more changes to the branch, haven't checked the broken create/restore wallet flow yet..

**Comment by zaSmilingIdiot** [comment]
> Also, balances overview in sidebar (under logo) are missing. Maybe an issue of merging / conflicts (in `src/app/core-ui/main/main-view.module.ts`?).

Yep, I think that might have been the case. Will get this fixed up.

**Comment by vikas-cis-zz** [comment]
Hye @AllienWorks 

I have more than 10 wallets and it seems it some stucks with the scroll and when it get scrolled to the botton then I tried to click on "+" icon but it just make me scroll up 

Screen Shot 2019-04-08 at 12 15 26 PM
Screen Shot 2019-04-08 at 12 15 34 PM

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot  Me and @cis-shubham-t has fixed all the test cases, please have a look and let us know if their is anything required

Thanks

**Comment by AllienWorks** [comment]
**Bug in Restore wallet**
When you name the wallet and confirm by `Enter` (not clicking on Next with mouse), you get thrown into Create wallet instead. By the time you realize this (at Recovery Phrase, which is filled out), you need to go few steps back and start the Restore flow again.

If you submit the wallet name with mouse, it's all working all right.

**Comment by spazzymoto** [comment]
@AllienWorks i pushed a fix for the restore issue

**Comment by AllienWorks** [comment]
> I have more than 10 wallets and it seems it some stucks with the scroll and when it get scrolled to the botton then I tried to click on "+" icon but it just make me scroll up

Fixed.

**Review by zaSmilingIdiot — APPROVED** [review]
With a lot of changes having happened in this branch, I think its looking good, and testing feedback seems positive. So LGTM :D

**Pull request merged**
