### PR TITLE
fixed window resizing issue

### PR DESCRIPTION
**Pull request by allienworks**
- locked window's min-width and min-height (on the same sizes as default width/height)
- enabled resizing & fullscreen

### CODE REVIEW

**Comment by allienworks** [comment]
**Don't merge into 1.1!**

**Comment by pciavald** [comment]
why not for 1.1 ?

**Comment by allienworks** [comment]
> @pciavald why not for 1.1 ?

Responsivity isn't solved for larger widths. You can pull and try for yourself.

**Comment by pciavald** [comment]
@allienworks can you please fix conflicting files ? :)

**Comment by allienworks** [comment]
@pciavald done.

**Comment by allienworks** [comment]
@kewde why did you merge this? :|
I didn't want this in 1.1, still needs fixing of responsivity for larger widths (see conversation ^)

**Pull request merged**
