### PR TITLE
Listing expiry time set as default 2 days.

### PR DESCRIPTION
**Pull request by cis-shubham-t**

### CODE REVIEW

**Comment by cis-shubham-t** [comment]
Task: https://particl.atlassian.net/projects/PBD/issues/PBD-248

**Comment by cis-shubham-t** [comment]
@AllienWorks 
Could you please make the error message nicer (like a red error message ).
shown in the first picture.
error message

I updated the estimation message stuff.
price with message

**Comment by cis-shubham-t** [comment]
Sorry @AllienWorks 
We removed the previous changed. So I believe now again all set no need to change anything.
Thanks

**Comment by zaSmilingIdiot** [comment]
Just noting why this change is required:

SMSG messages are currently either paid or free. Listings, and proposals, generate paid-for messages. Whereas voting uses free messages. The current network retention period for free messages is 2 days, for paid messages its 31 days. However, listing removal votes and proposal voting options need to run the duration of the "source" paid message (ie: the listing item or proposal), in order to prevent different views where client nodes are off network for a period of time and do not receive all/any of the vote messages.

Longer term solutions are being determined and worked on currently, but this change provides a short term fix by limiting the paid for messages generated to be a maximum of 2 days. Which ensures that all messages (free and paid) can run for the same duration.

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
