### PR TITLE
fixed the fact that you couldnt leave the error screen

### PR DESCRIPTION
**Pull request by EagleEye25**

### CODE REVIEW

**Comment by EagleEye25** [comment]
there will be some styling for the button that has to be done.
@AllienWorks if you wouldnt mind doing this for us :D
ss 2018-12-21 at 11 50 44
this is what it currently looks like :(

**Comment by AllienWorks** [comment]
@EagleEye25 I've styled it, it's ready for review.
Btw the last screen appears only with errors, right?

**Comment by EagleEye25** [comment]
@AllienWorks, this shows both when there are errors and when there isnt

**Comment by EagleEye25** [comment]
@AllienWorks yes, this only shows when there is errors
@zaSmilingIdiot  this is ready for Review

**Review by zaSmilingIdiot — APPROVED** [review]
I'm not a big fan of setting global values for single state (step) content within a component. But it does work here, so for the sake of moving things along, it good enough :)

**Pull request merged**
