### PR TITLE
Multiwallet & Installer

### PR DESCRIPTION
**Pull request by AllienWorks**
screenshot from 2018-07-13 15-39-28

- sidebar with selection of available wallets (layout only)
- more info about this on Paper (doc called "Setup wizard")
- old Multiwallet PR for reference: https://github.com/particl/particl-desktop/pull/441

## Testing instructions
1. Run the following daemon `https://transfer.sh/zYMcL/particld` (linux x64)
2. Patch Angular with a bug fix:
Open the file `/node_modules/@angular/router/esm5/router.js` & go to line 2056.
Add the `&& !route._loadedConfig.module._destroyed`

```
            // lazy children belong to the loaded module
            if (route._loadedConfig !== undefined && !route._loadedConfig.module._destroyed) {
                return of(route._loadedConfig);
            }
```

## TODO

- [x] add the updater to the loading screen (instead of a modal)
- [x] fix the styling issues on the password boxes (@AllienWorks )
- [x] new wallets aren't created (?)
- [x] mutiple wallets don't appear in MW sidebar (not even the first/default one)

### Create wallet

- **Choose create/recovery**
    - [ ] `Encrypt wallet` button not working (we're encrypting the new wallet in further steps, should we remove it?)
- **Name wallet**
    - [ ] When wallet name already exists, you can't get past the "Name wallet" step - I suggest the snackbar notification with "wallet name already exists" (or [show error directly in input](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown))
- **Recovery Phrase**
    - [x] console complains about `ERROR Error: Found the synthetic property @transitionMessages. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`
- **Confirm Recovery Phrase**
    - [x] none of the words are missing (everything is pre-filled)
- **Recovery Pass**
    - [x] move "Passwords do not match" error message [directly to input](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown) - already prepared with `mat-hint`
    - [x] disable `Continue` button if passwords do not match
- **New wallet created**
    - [ ] wallet gets stuck (doesn't load TXs, balances, ..), 2 cold staking widgets are shown, other pages not working/loading as well

### Recover wallet

- **Phrase/Password**
    - [ ] `Continue` button stays enabled if Recovery Phrase includes invalid words (in red)
    - [ ] after submitting Phrase/Pass, user is redirected to blank page

### CODE REVIEW

**Comment by AllienWorks** [comment]
### TODO

- [ ] @kewde on init load of app, the "Overview" page title is missing (when you click other tabs and go back, it shows up OK)

**Comment by kewde** [comment]
Blocked until https://github.com/angular/angular/pull/24987

**Comment by AllienWorks** [comment]
### Few UX/bug TODOs

- **Choose create/recovery**
    - [ ] `Encrypt wallet` button not working (we're encrypting the new wallet in further steps, should we remove it?)
- **Name wallet**
    - [ ] When wallet name already exists, you can't get past the "Name wallet" step - I suggest the snackbar notification with "wallet name already exists" (or [show error directly in input](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown))
- **Recovery Phrase**
    - [ ] takes a lot of time to generate (with broken layout until finished)
        - can we hide it & display loading spinner & disable `Continue` button until loaded?
    - [ ] console complains about `ERROR Error: Found the synthetic property @transitionMessages. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`
- **Confirm Recovery Phrase**
    - [ ] none of the words are missing (everything is pre-filled)
- **Recovery Pass**
    - [ ] move "Passwords do not match" error message [directly to input](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown) - already prepared with `mat-hint`
    - [ ] disable `Continue` button if passwords do not match

**Comment by kewde** [comment]
I'm pretty sure the following two are caused by you not running the right daemon, marking them as solved for now.
- [ ] new wallets aren't created (?)
- [ ] mutiple wallets don't appear in MW sidebar (not even the first/default one)

**Comment by zaSmilingIdiot** [comment]
I do not have access to edit the OP comment, but I can verify that the TODO item
  -  multiple wallets don't appear in MW sidebar (not even the first/default one)

is not resolved.

**Comment by kewde** [comment]
Next 0.17 rc3 will not require a reboot of the wallet after encrypting.

**Comment by kewde** [comment]
To backport/fix:
https://github.com/particl/particl-desktop/pull/1096/files#diff-d4bc0f0baba09245a4006408e1b919b7

Revert to arch = 'mac'

**Comment by zaSmilingIdiot** [comment]
This has been replaced by #1488 

The changed included therein are based off of these changes, along with some modifications, tweaks, and updates. Further updates will continue in that branch/Pull Request.

The patching problem is no longer necessary, as the patch required here no longer appears to be applicable with Angular 7. While the angular version could be patched, this forces the problem of determining whether and where to apply various patches each time the angular dependency changes. Changes have been made accordingly.

**Pull request closed without merging**
