### PR TITLE
Listing filtering

### PR DESCRIPTION
**Pull request by vikas-cis-zz**
https://particl.atlassian.net/browse/PD-367

### CODE REVIEW

**Comment by zaSmilingIdiot** [comment]
@vikas-cis Is this still waiting for changes from the particl-marketplace codebase to be implemented/fixed?

**Comment by vikas-cis-zz** [comment]
> @vikas-cis Is this still waiting for changes from the particl-marketplace codebase to be implemented/fixed?

I think so, but just wondering have you tested it ?

**Review by zaSmilingIdiot — CHANGES_REQUESTED** [review]
Hmmm... something breaks here. When using this particular branch of code, I don't see any published/unpublished listings in the Sell page. All other code branches show the existing ones that should be there.

Seems like something has broken...

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot are you running the marketplace manually ? 

Thanks

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot  there are changes has been made in this branch for template search, If you are not running the latest develop branch code then I think you will get error in console for sure :P :D 

Thanks

**Comment by zaSmilingIdiot** [comment]
@vikas-cis Ah, no. develop branch of the marketplace?

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot  yes afaik the laz branch has been merged in develop branch

Thanks

**Comment by zaSmilingIdiot** [comment]
@vikas-cis I'll give the code a quick look overview, and we can chat offline about any changes needed. I'm not necessairly going to merge the changes yet though, until https://github.com/particl/particl-market/pull/333 has been merged.

I'm just mentioning this for why I removed the 'ready for review' tag.

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot  yeah ofcourse I still need to test the branch again has yesterday I am facing issue and it was fixed via laz so going to give a quick check on it

Thanks

**Comment by AllienWorks** [comment]
Jumping issue with content just fixed @vikas-cis. That wraps it for me :)

**Comment by vikas-cis-zz** [comment]
Thanks @AllienWorks Will check it out in a bit

**Comment by vikas-cis-zz** [comment]
ok @zaSmilingIdiot we are good to go now the below PR from marketplace did it for us.

https://github.com/particl/particl-market/pull/352

**Comment by vikas-cis-zz** [comment]
https://particl.atlassian.net/browse/PBD-176
the above task is also covered @zaSmilingIdiot @HenkSwardt 

Thanks

**Comment by vikas-cis-zz** [comment]
Hye @zaSmilingIdiot I have tested with different scenarios add listing , update listing , publish un-published listing , edit listing and it seems working well to me so  now we can merge this branch . I have tested with marketplace running mannually 

Thanks

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
