### PR TITLE
Community Test Build 20190205

### PR DESCRIPTION
**Pull request by zaSmilingIdiot**

### CODE REVIEW

**Comment by zaSmilingIdiot** [comment]
Job done... no need to keep this around

**Comment by LiteBit** [comment]
would it make sense to keep open for the 10 day download window at least?

**Comment by zaSmilingIdiot** [comment]
Maybe, but the purpose of the PR was just to trigger the build step. The next community test build will be taken off the market-beta branch, not this specific branch/PR, and the changes included here are simply here to provide a manual build number (I'm not going to merge this anyway back into the market-beta branch.

But, if it makes people feel warm and fuzzy that the PR is still open for the next couple of days, I'll be happy to re-open it :smiley_cat:

**Comment by HenkSwardt** [comment]
I also dont feel that we need to keep this open. 

As per @zaSmilingIdiot , this was only created for the build process.

**Comment by LiteBit** [comment]
as long as links point back here it's fine to leave as is

**Pull request closed without merging**
