### PR TITLE
Improve router

### PR DESCRIPTION
**Pull request by kewde**
Blocked by #764 

- [x] Reworked the router, we now have a core-router.
- [x] Move the big modals to the views

### CODE REVIEW

**Comment by allienworks** [comment]
Styled the splash loading and cleaned-up a bit:

**Comment by pciavald** [comment]
so many conflicting files 😮 
@allienworks animations now work while loading ?

**Comment by allienworks** [comment]
> @pciavald animations now work while loading ?

Technically no, the loading screen itself is now empty and just flashes for a second. Then this "new" loading view takes place and it works. Maybe it's also because of the animations being done in pure CSS..

**Comment by anandsinghparihar** [comment]
@kewde I 
- [ ] Wallet Initially with blank modal open (encryption modal I guess).
black modal box


- [ ] Zap functionality is not working not working.

- [ ] If I created wallet without encryption then after wallet created I cant able to set the encryption key.

**Comment by anandsinghparihar** [comment]
If I created a wallet using enter button then it says wallet created but actually not !! 
https://www.useloom.com/share/1a29d7cf33fc4a8aaee9e980bc1995db

**Comment by kewde** [comment]
state service failure is fixed in #797

**Pull request closed without merging**
