### PR TITLE
crash when downloading daemon timeouts 

### PR DESCRIPTION
**Pull request by anandsinghparihar**
https://github.com/particl/particl-desktop/issues/751

### CODE REVIEW

**Comment by anandsinghparihar** [comment]
@kewde please check last commit I guess ` windows binPath` also cover !!

**Comment by anandsinghparihar** [comment]
@EagleEye25 could you please test it in windows

**Comment by EagleEye25** [comment]
`$ npm run start:electron:dev -- -testnet

> particl-desktop@1.1.0 start:electron:dev A:\@work\partgui
> electron . --dev "-testnet"


[08:57:07.830] [debug] console log level: silly
[08:57:07.832] [debug] file log level: warn
[08:57:08.391] [debug] app ready
[08:57:08.516] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:08.518] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:08.530] [info] Initializing...
[08:57:08.531] [info] Resolving path to client binary ...
[08:57:08.531] [debug] Platform: win
[08:57:08.531] [info] No such a directory Particl Desktop.
[08:57:08.531] [info] Client binary path: undefined
[08:57:08.532] [info] Checking for new client binaries config from: https://raw.githubusercontent.com/particl/particl-desktop/dev/modules/clientBinaries/clientBinaries.json
[08:57:08.532] [debug] Status: loadConfig - Fetching remote client config
[08:57:13.539] [warn] Error fetching client binaries config from repo Error: Request timed out
    at timeoutFn (A:\@work\partgui\node_modules\got\index.js:288:53)
    at asPromise (A:\@work\partgui\node_modules\got\index.js:358:18)
    at got (A:\@work\partgui\node_modules\got\index.js:588:10)
    at DaemonManager._checkForNewConfig (A:\@work\partgui\modules\daemon\daemonManager.js:69:12)
    at DaemonManager.init (A:\@work\partgui\modules\daemon\daemonManager.js:43:17)
    at daemon.check.then.catch (A:\@work\partgui\modules\init.js:18:42)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

[08:57:13.542] [info] No config for the ClientBinariesManager could be loaded, using local clientBinaries.json.
[08:57:13.544] [error] Error: Cannot find module './clientBinaries.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (A:\@Work\partgui\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at got.then.catch.then.then (A:\@work\partgui\modules\daemon\daemonManager.js:206:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

[08:57:13.544] [debug] Status: error - Cannot find module './clientBinaries.json'
[08:57:13.546] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:13.547] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:13.549] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:13.551] [info] starting daemon undefined --dev,-testnet
(node:13992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Bad argument
(node:13992) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[08:57:16.573] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:16.576] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:16.577] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:16.578] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:16.580] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:16.646] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:16.647] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:19.267] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:19.273] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:19.300] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:19.302] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:26.583] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:26.586] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:29.305] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:29.312] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:29.315] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:29.316] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:36.585] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:36.588] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:39.318] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:39.323] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:39.328] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:39.333] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:46.587] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:46.592] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:49.345] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:49.347] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:49.350] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:49.353] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:56.597] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:56.600] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:59.359] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:59.361] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:59.364] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
[08:57:59.366] [debug] could not find cookie file! path: C:\Users\Jay\AppData\Roaming\Particl/testnet/.cookie
`
this was my terminal output after testing, followed all steps that were listed on the issue for testing

**Comment by EagleEye25** [comment]
update: app never stops looking for cookie file

**Comment by kewde** [comment]
@EagleEye25 it's being called everytime an RPC call is made, grabs the latest user:password each time.
It's kinda nice as every reboot it takes the latest, reboots of particl-daemon change the user:password.

**Comment by anandsinghparihar** [comment]
@kewde is there anything which I can do on this issue?

**Comment by anandsinghparihar** [comment]
@kewde its working fine in windows I cant see any js error box now :)

**Comment by anandsinghparihar** [comment]
@kewde this PR is ready for review

**Pull request merged**
