### PR TITLE
Inventory management

### PR DESCRIPTION
**Pull request by AllienWorks**
### Done

- prepared layout for Quantities

### Notes

- Qty is displayed as a range (eg. 1–5, 6–10 etc.), see [PBD-107](https://particl.atlassian.net/browse/PBD-107) for more info
- minumum for Qty should always be 1
- maximum should be what Sellers has in stock

### Todo

Quantities are affecting quite a lot of components, they need to be implemented in:

- [ ] `checkout-process.component.html:82,88,296`
- [ ] `preview-listing.component.html:71`
- [ ] `add-item.component.html:71`
- [ ] `seller-listing.component.html:48`
- [ ] `add-to-cart.component.html:10`
- [ ] `order-item.component.html:48`

That should be all.

---

- [ ] Buy flow: rejecting bids when not enough items in stock @AllienWorks

### CODE REVIEW

**Comment by AllienWorks** [comment]
I'm need to wait for `particl-market` update to latest version to continue. Can't create new Listings now, so I'll come back to the "rejecting bids when not enough items in stock" later - @HenkSwardt FYI.

So far the Quantity layout is in place for whoever dev that should implement it.

**Comment by AllienWorks** [comment]
I've pushed this PR up-to-date with `market-beta`, but my market isn't working for some reason..
Nevertheless you can work on this and implement the quantities.

**Comment by AllienWorks** [comment]
@HenkSwardt @zaSmilingIdiot this is done from my side & ready for implementation. All the places where inventory needs to be imlpemented are noted in the top comment.

**Edit:** [Inventory preview](https://imgur.com/a/IUqVaur) gallery

**Comment by zaSmilingIdiot** [comment]
Closing this due to re-organization of this repo. Pull request owner is aware of the update, and will be able to re-submit this PR when/where applicable.

Note: has already been migrated

**Pull request closed without merging**
