### PR TITLE
Multiwallet

### PR DESCRIPTION
**Pull request by AllienWorks**
Preview: https://imgur.com/a/Vtcce

- [x] added layout for selecting different wallets
- [ ] when more `wallet.dat` files are present in the Particl folder, launch modal on startup
- [x] display multiselect menu in this modal ^ with available `wallet.dat` files to load
- [x] ..and style it

@vikas-cis @anandsinghparihar: could one of you help me out with the modal?

### CODE REVIEW

**Comment by kewde** [comment]
I wouldn't use a modal in this situation..

Instead on boot I would load a new screen, that makes you select the wallet as displayed in this bar & then a small login screen? So on boot you have to unlock your wallet once before you enter it? 

The new routing allows us to easily swap to new views. You can have full-width page without the typical sidebar etc.

**Comment by kewde** [comment]
I wouldn't use a modal in this situation..

Instead on boot I would load a new screen, that makes you select the wallet as displayed in this bar & then a small login screen? So on boot you have to unlock your wallet once before you enter it? 

The new routing allows us to easily swap to new views. You can have full-width page without the typical sidebar etc.

**Comment by anandsinghparihar** [comment]
@allienworks, I've just opened a full-width multi wallet modal.  Now you can start work on design section. 

this is just a temporary dialog box, when you complete design @pciavald will manage that modal.

**Comment by pciavald** [comment]
thanks @anandsinghparihar. @kewde we'll start with the fullscreen modal to that @allienworks can do the design work, then I'll move it to a new screen. When you have the time, can you please explain exactly how to do it / where it's done ?

**Comment by allienworks** [comment]
@pciavald I'm done, passing this onto you. If you need anything, let me know.

**Comment by pciavald** [comment]
https://github.com/particl/particl-desktop/blob/f23ae74afa7728a8d460e8a344297ef647f3e4ef/src/app/core-ui/main/status/modal/help-modal/console-modal.component.ts#L61

**Comment by pciavald** [comment]
https://particl.atlassian.net/browse/PAR-180

**Comment by vikas-cis** [comment]
@pciavald I am checking the travis issue

**Pull request closed without merging**
