### PR TITLE
fixed clone listing

### PR DESCRIPTION
**Pull request by EagleEye25**
added changes due to backend changes to allow the images to be shown when cloning a listing.

### CODE REVIEW

**Comment by zaSmilingIdiot** [comment]
Which particl-marketplace pull request does this depend on?

**Comment by EagleEye25** [comment]
> Which particl-marketplace pull request does this depend on?

https://github.com/particl/particl-market/pull/356

**Comment by zaSmilingIdiot** [comment]
Note: internal development issue item is https://particl.atlassian.net/browse/PBD-181

**Comment by zaSmilingIdiot** [comment]
Added the waiting tag to reflect the dependency on the merging of the particl-market branch mentioned previously.

**Comment by EagleEye25** [comment]
no longer waiting on market merge

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
