### PR TITLE
Convert settings page design into material

### LINKED ISSUE #582: Finalize GUI Settings page
We need to wrap up the development on the GUI Settings page. Please can we discuss and finalize specification on this issue.

See below screen of design.

particl_wallet_settings

### PR DESCRIPTION
**Pull request by anandsinghparihar**
Closes #582

### CODE REVIEW

**Comment by allienworks** [comment]
I propose a new structure for the Settings page:

- move _Main > Staking, Transactions_ to separate tab (Main page is already crowded as it is..)
- move whole _Window_ to _Main_ tab (too little options for own page)
- add info to _Help_ tab as per #540 
- add _About_ page, which could contain some credits to used tech/code, current version display etc. & possibly even contributors ;)

What do you think?

**Comment by allienworks** [comment]
Current preview: https://i.imgur.com/btjvUPY.mp4 (available also as a [10MB GIF](https://i.imgur.com/btjvUPY.gif) :)

### TODO

- quite a lot the settings still needs to be connected to backend; I haven't tested all, but many of those don't work
- we'll need to review all the items and hide the irrelevant (e.g. Secure messaging, which AFAIK isn't available anywhere in the GUI yet)
- add a lot of stuff (from the top of my head stuff related to Cold staking etc.)
- proof-reading and someone to actually come up with senseful descriptions and help texts! :)

**Comment by kewde** [comment]
Going to merge, better to have this in the codebase.
I've hidden  the settings page for now

**Comment by AllienWorks** [comment]
@kewde yes please, the merge of this is long overdue. I've defined some SCSS templates etc. which I would like to use globally in app. So by me yes, definitely merge this :)

**Pull request closed without merging**
