### PR TITLE
added the button to load report listing

### PR DESCRIPTION
**Pull request by vikas-cis-zz**
https://particl.atlassian.net/browse/PD-465

### CODE REVIEW

**Comment by vikas-cis-zz** [comment]
@AllienWorks  I have added the button on the listing page please have a look and let me know if there is anything that we need to add.

Thanks

**Comment by AllienWorks** [comment]
Hey @vikas-cis, I've included the toggle button (+ replaced the old code).

**Comment by zaSmilingIdiot** [comment]
Waiting for marketplace changes to be implemented before including these changes.

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot please have a look and let me know if it  looks good :)

Thanks

**Comment by HenkSwardt** [comment]
Dependent on the merge of https://github.com/particl/particl-market/pull/329

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
