### PR TITLE
Send combinations fix

### PR DESCRIPTION
**Pull request by vikas-cis-zz**

### CODE REVIEW

**Comment by zaSmilingIdiot** [comment]
references #1274

**Review by zaSmilingIdiot — CHANGES_REQUESTED** [review]
The current changes do not resolve the reported issue. In the Send page > Convert Public to Private tab,  selecting a radio button in the PAY FROM group does correctly "grey out" the corresponding radio button in the CONVERT TO group. 

However, as an example, with the 'Anon' option selected in the Pay From group, it is still not possible to select the 'Blind' option in the Convert To group. This needs to be fixed.

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot yeah the last scenario for selecting anon => blind to viceversa is still left which I am working and testing, Once it get fixed will push the change 

Thanks

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot please have a look and let me know 

Thanks

**Comment by vikas-cis-zz** [comment]
https://particl.atlassian.net/browse/PD-477

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
