### PR TITLE
created modal for rejection message

### PR DESCRIPTION
**Pull request by EagleEye25**

### CODE REVIEW

**Comment by EagleEye25** [comment]
@AllienWorks when you arent busy, would you please do some styling on the reject-bid modal for us :D please and thank you.
please note that im waiting for changes on the market side to be completed first, so this isnt high priority.

**Comment by EagleEye25** [comment]
@AllienWorks changes have been completed, you are free to do styling :P
styling on:
rejection message modal,
label on the orders

**Comment by AllienWorks** [comment]
### TODO

- [x] style rejection message modal
- [x] style label of rejected orders (`order-item-component.html:33`):

```
<code class="more-info">{{ checkRejectMessage() }}</code>
```

**Comment by EagleEye25** [comment]
karam tests are executing 100% when running locally, seems to be an issue on the travis side where it fails..

**Comment by AllienWorks** [comment]
I've styled the rejection modal, BUT:
- it doesn't reject the bids (button doesn't do anything)
- we already have one rejection modal in [`place.order:75`](https://github.com/EagleEye25/partgui/blob/reject-messages/src/app/modals/market-place-order/place-order.component.html#L75), so either we might want to use that or get rid of it

Screenshot from 2019-03-13 18-01-35

(Note, this PR is related to #1373)

**Comment by vikas-cis-zz** [comment]
I have tested and confirm there are few concerns with marketplace regarding the messages are not returning currently

Thanks

**Comment by vikas-cis-zz** [comment]
ok @zaSmilingIdiot  I think we can remove WIP and make it ready for review , Afaik all the changes required has been done.

Thanks

**Comment by zaSmilingIdiot** [comment]
Closing this due to re-organization of this repo. Pull request owner is aware of the update, and will be able to re-submit this PR when/where applicable.

Note: has already been migrated.

**Pull request closed without merging**
