### PR TITLE
added the tooltip to show the rest of the content of category and cou…

### PR DESCRIPTION
**Pull request by vikas-cis-zz**
…ntry

### CODE REVIEW

**Comment by vikas-cis-zz** [comment]
https://particl.atlassian.net/browse/PD-363

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot I have added tooltip for the content of category to show, let me know if that looks good :)

Thanks

**Comment by zaSmilingIdiot** [comment]
@vikas-cis The change in itself is perfectly fine, however:

I suspect there might be a comment missing in PD-363. If I remember correctly, the discussion had on this item included the ability to show only the top level category items in the menu initially, and then when clicked on, a top level category would expand to show the sub-category items. @AllienWorks I'm hoping you might have some further clarity on this: do you recall if this was the case or if that requirement was meant to be moved to another issue?

**Comment by vikas-cis-zz** [comment]
@zaSmilingIdiot may be that change is not included in this bug list or whatever :P :D 
thanks

**Comment by zaSmilingIdiot** [comment]
My previous comment on this has been resolved: a new issue will be created for the changing of menu options between category and sub-category menu items. Which leaves this change to only cater for adding the tooltip to the menu options.

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
