### PR TITLE
PBD-264 - Add ability to filter flagged (for removal) items on listing view

### PR DESCRIPTION
**Pull request by spazzymoto**
This PR requires particl-market PR (https://github.com/particl/particl-market/pull/385)

### CODE REVIEW

**Comment by zaSmilingIdiot** [comment]
Looks to be similar to https://github.com/particl/particl-desktop/pull/1538

**Comment by zaSmilingIdiot** [comment]
Waiting for the inclusion of the changes requested in the particl-marketplace before actioning this.

**Comment by spazzymoto** [comment]
@zaSmilingIdiot you are right, didn't realize Shubham had already done the desktop work. Should i rather close this one?

**Comment by zaSmilingIdiot** [comment]
Nah, leave it open for now: both can be evaluated just in case.

**Pull request closed without merging**
