### PR TITLE
Cart expired items

### PR DESCRIPTION
**Pull request by EagleEye25**

### CODE REVIEW

**Comment by EagleEye25** [comment]
@AllienWorks i did some simple styling on the listings that have expired, what we would require from you is to please style it in a correct way that would look correct within the way that all the styling is done, please and thank you :D

**Comment by AllienWorks** [comment]
@EagleEye25 I have the changes ready, but can't push to your repo (don't have the permissions). Can you please add me as collaborator? Once you will, I will push my stuff ;)

For others, here's a teaser :)

screenshot from 2018-12-17 17-52-39

I'm thinking that we might also hide the category name if error is present, that would make it even nicer. After all, category doesn't really help you with expired listings anyway..

**Comment by EagleEye25** [comment]
@AllienWorks ive sent you an invite to be a collaborator on my repos. I really like the way you did the styling looks awesome. Thank you

**Comment by AllienWorks** [comment]
@EagleEye25 thanks! Now you can check it out yourself live :)

@zaSmilingIdiot ready for review, I believe!

**Comment by zaSmilingIdiot** [comment]
@EagleEye25 can we hide the category item if errors occur? Otherwise the category needs to move above the error message.

**Review by zaSmilingIdiot — APPROVED** [review]

**Pull request merged**
